#!/bin/bash
# SDR Relayer One-Click Installer
# Usage: curl -fsSL https://web-production-554d8.up.railway.app/install.sh | bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   SDR Relayer One-Click Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Server URL
SERVER_URL="https://web-production-554d8.up.railway.app"
INSTALL_DIR="$HOME/sdr-relayer"

# ============================================
# Step 1: Check macOS
# ============================================
echo -e "${YELLOW}[1/6]${NC} Checking system requirements..."

if [[ "$OSTYPE" != "darwin"* ]]; then
    echo -e "${RED}Error: This installer only works on macOS${NC}"
    echo "The relayer requires macOS for Telegram automation."
    exit 1
fi
echo -e "  ${GREEN}✓${NC} macOS detected"

# ============================================
# Step 2: Check/Install Node.js
# ============================================
echo -e "${YELLOW}[2/6]${NC} Checking Node.js..."

if ! command -v node &> /dev/null; then
    echo -e "  ${YELLOW}Node.js not found. Installing...${NC}"

    # Check for Homebrew first
    if command -v brew &> /dev/null; then
        echo "  Installing via Homebrew..."
        brew install node
    else
        echo -e "  ${YELLOW}Homebrew not found. Installing Homebrew first...${NC}"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

        # Add Homebrew to PATH for this session (Apple Silicon)
        if [[ -f "/opt/homebrew/bin/brew" ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
        fi

        brew install node
    fi
fi

NODE_VERSION=$(node --version)
echo -e "  ${GREEN}✓${NC} Node.js $NODE_VERSION"

# ============================================
# Step 3: Check Telegram Desktop
# ============================================
echo -e "${YELLOW}[3/6]${NC} Checking Telegram Desktop..."

if [[ -d "/Applications/Telegram.app" ]] || [[ -d "$HOME/Applications/Telegram.app" ]]; then
    echo -e "  ${GREEN}✓${NC} Telegram Desktop found"
else
    echo -e "  ${YELLOW}!${NC} Telegram Desktop not found"
    echo ""
    echo "  Please install Telegram Desktop:"
    echo "  https://desktop.telegram.org/"
    echo ""
    read -p "  Press ENTER after installing Telegram Desktop..." < /dev/tty
fi

# ============================================
# Step 4: Download and Install
# ============================================
echo -e "${YELLOW}[4/6]${NC} Downloading relayer package..."

# Remove old installation if exists
if [[ -d "$INSTALL_DIR" ]]; then
    echo "  Removing old installation..."
    rm -rf "$INSTALL_DIR"
fi

mkdir -p "$INSTALL_DIR"

# Download and extract
echo "  Downloading from $SERVER_URL..."
curl -fsSL "$SERVER_URL/relayer-package.tar.gz" | tar -xzf - -C "$INSTALL_DIR" --strip-components=1

if [[ ! -f "$INSTALL_DIR/relayer-client.js" ]]; then
    echo -e "${RED}Error: Download failed. relayer-client.js not found.${NC}"
    exit 1
fi

echo -e "  ${GREEN}✓${NC} Package downloaded to $INSTALL_DIR"

# Install npm dependencies
echo "  Installing dependencies (this may take a minute)..."
cd "$INSTALL_DIR"
npm install --production --silent 2>/dev/null || npm install --production

echo -e "  ${GREEN}✓${NC} Dependencies installed"

# ============================================
# Step 5: Configure Credentials
# ============================================
echo ""
echo -e "${YELLOW}[5/6]${NC} Configure your credentials"
echo ""

# Read from /dev/tty to handle piped execution (curl | bash)
read -p "  Enter your name (e.g., Jenny, Mike): " EMPLOYEE_ID < /dev/tty
if [[ -z "$EMPLOYEE_ID" ]]; then
    echo -e "${RED}Error: Username is required${NC}"
    exit 1
fi

echo ""
echo "  Get the API key from your manager:"
read -p "  ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY < /dev/tty
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
    echo -e "${RED}Error: ANTHROPIC_API_KEY is required${NC}"
    exit 1
fi

# Create .env.local
cat > "$INSTALL_DIR/.env.local" <<EOF
# SDR Relayer Configuration
# Generated by install script on $(date)

RENDER_URL=$SERVER_URL
EMPLOYEE_ID=$EMPLOYEE_ID
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
POLL_INTERVAL_MS=2000
EOF

echo -e "  ${GREEN}✓${NC} Configuration saved"

# ============================================
# Step 6: Mac Permissions
# ============================================
echo ""
echo -e "${YELLOW}[6/6]${NC} Grant macOS Accessibility Permission"
echo ""
echo -e "  ${YELLOW}This is required for Telegram automation to work.${NC}"
echo ""
echo "  In the window that opens:"
echo "  1. Click the lock icon to unlock"
echo "  2. Click + and add Terminal (or your terminal app)"
echo "  3. Make sure the checkbox is enabled"
echo ""
read -p "  Press ENTER to open System Settings..." < /dev/tty

# Open System Settings to Accessibility
open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"

echo ""
read -p "  Press ENTER after granting permission..." < /dev/tty

# ============================================
# Done!
# ============================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} Relayer installed to: $INSTALL_DIR"
echo -e "  ${GREEN}✓${NC} Credentials configured"
echo ""
echo "  To start the relayer:"
echo ""
echo -e "    ${BLUE}cd ~/sdr-relayer && npm run relayer${NC}"
echo ""
echo "  Web UI: $SERVER_URL"
echo ""

# Ask if they want to start now
read -p "  Start the relayer now? (Y/n): " START_NOW < /dev/tty
START_NOW=${START_NOW:-Y}

if [[ "$START_NOW" =~ ^[Yy]$ ]]; then
    echo ""
    echo "  Starting relayer..."
    echo "  (Press Ctrl+C to stop)"
    echo ""
    npm run relayer
else
    echo ""
    echo "  To start later, run:"
    echo "    cd ~/sdr-relayer && npm run relayer"
    echo ""
fi
